# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.1'

gem 'acts_as_tenant', '~> 1.0.1'
gem 'bootsnap', require: false
gem 'cssbundling-rails'
gem 'devise'
gem 'devise-i18n'
gem 'jbuilder'
gem 'jsbundling-rails'
gem 'kaminari'
gem 'kaminari-bootstrap'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.3', '>= 7.1.3.4'
gem 'simple_form'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem "image_processing", "~> 1.2"
gem 'webpacker', '~> 5.4'


group :development, :test do
  gem 'annotate', '~> 3.1', '>= 3.1.1'
  gem 'better_errors', '~> 2.9', '>= 2.9.1'
  gem 'binding_of_caller', '~> 1.0'
  gem 'brakeman', '~> 5.2'
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'rails-controller-testing'
  gem 'rails-erd'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubycritic'
  gem 'shoulda-matchers'
  gem 'simplecov'
end

group :development do
  gem 'web-console'
  gem 'letter_opener_web'
end
